name: Keep PR Updated
description:
  An action that keeps your pull requests up to date with the base branch.
author: alfred82santa

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-merge
  color: red

# Define your inputs here.
inputs:
  github-token:
    description: 'GitHub token to use for authentication.'
    required: true
    default: '${{ github.token }}'
  base-branch:
    description: 'The base branch to keep the pull requests updated with.'
    required: true
    default: '${{ github.event.pull_request.base.ref || github.ref_name }}'
  required-labels:
    description:
      'Comma-separated list of labels required to trigger the update.'
    required: false
    default: ''
  required-automerge:
    description:
      'If true, only update the PR if it has the "automerge" enabled.'
    required: false
    default: 'false'
  avoided-labels:
    description:
      'Comma-separated list of labels that prevent the update if present on the
      PR.'
    required: false
    default: ''
# Define your outputs here.
outputs:
  pull-requests-updated:
    description: 'Indicates which pull requests have been updated.'
  pull-requests-skipped:
    description: 'Indicates which pull requests were skipped.'
  pull-requests-failed:
    description: 'Indicates what pull requests failed to update.'

runs:
  using: node24
  main: dist/index.js
